export const BRAND_COMMAND_REPOSITORY = Symbol('BRAND_COMMAND_REPOSITORY');
export const BRAND_QUERY_REPOSITORY = Symbol('BRAND_QUERY_REPOSITORY');
export const BRAND_MEDIA_UPLOAD_HANDLER = Symbol('BRAND_MEDIA_HANDLER');
export const BRAND_MEDIA_DELETE_HANDLER = Symbol('BRAND_MEDIA_HANDLER');
