services:
    smart-tech-db:
        image: mysql:8.0
        container_name: mysql
        ports:
            - 3306:3306
        restart: always
        env_file:
            - .env
    smart-tech-redis:
        image: redis
        ports:
            - 6379:6379
        env_file:
            - .env
