export const VOUCHER_TOKENS = {
    REPOSITORIES: {
        VOUCHER_QUERY_REPOSITORY: Symbol('VOUCHER_QUERY_REPOSITORY'),
        VOUCHER_COMMAND_REPOSITORY: Symbol('VOUCHER_COMMAND_REPOSITORY'),
    },

    SERVICES: {
        VOUCHER_QUERY_SERVICE: Symbol('VOUCHER_QUERY_SERVICE'),
        VOUCHER_COMMAND_SERVICE: Symbol('VOUCHER_COMMAND_SERVICE'),
    },
};
