export const USER_TOKENS = {
    REPOSITORIES: {
        USER_QUERY_REPOSITORY: 'USER_QUERY_REPOSITORY',
        USER_COMMAND_REPOSITORY: 'USER_COMMAND_REPOSITORY',
    },

    HANDLERS: {
        USER_MEDIA_HANDLER: 'USER_MEDIA_HANDLER',
        USER_PASSWORD_HANDLER: 'USER_PASSWORD_HANDLER',
    },

    SERVICES: {
        USER_QUERY_SERVICE: 'USER_QUERY_SERVICE',
        USER_COMMAND_SERVICE: 'USER_COMMAND_SERVICE',
        USER_MEDIA_SERVICE: 'USER_MEDIA_SERVICE',
    },
};
