export const PRODUCT_TOKENS = {
    REPOSITORIES: {
        PRODUCT_COMMAND: Symbol('PRODUCT_COMMAND_REPOSITORY'),
        PRODUCT_QUERY: Symbol('PRODUCT_QUERY_REPOSITORY'),
        VARIANT_COMMAND: Symbol('VARIANT_COMMAND_REPOSITORY'),
        VARIANT_QUERY: Symbol('VARIANT_QUERY_REPOSITORY'),
        COMBO_COMMAND: Symbol('COMBO_COMMAND_REPOSITORY'),
        COMBO_QUERY: Symbol('COMBO_QUERY_REPOSITORY'),
    },
    SERVICES: {
        PRODUCT_COMMAND: Symbol('PRODUCT_COMMAND_SERVICE'),
        PRODUCT_QUERY: Symbol('PRODUCT_QUERY_SERVICE'),
        VARIANT_COMMAND: Symbol('VARIANT_COMMAND_SERVICE'),
        VARIANT_QUERY: Symbol('VARIANT_QUERY_SERVICE'),
        COMBO_COMMAND: Symbol('COMBO_COMMAND_SERVICE'),
        COMBO_QUERY: Symbol('COMBO_QUERY_SERVICE'),
    },
    HANDLERS: {
        MEDIA: Symbol('PRODUCT_MEDIA_HANDLER'),
    },
};
