export const NEWS_COMMAND_REPOSITORY = Symbol('NEWS_COMMAND_REPOSITORY');
export const NEWS_QUERY_REPOSITORY = Symbol('NEWS_QUERY_REPOSITORY');
export const NEWS_MEDIA_UPLOAD_HANDLER = Symbol('NEWS_MEDIA_UPLOAD_HANDLER');
export const NEWS_MEDIA_DELETE_HANDLER = Symbol('NEWS_MEDIA_DELETE_HANDLER');
