export const CATEGORY_TOKENS = {
    REPOSITORIES: {
        COMMAND: Symbol('CATEGORY_COMMAND_REPOSITORY'),
        QUERY: Symbol('CATEGORY_QUERY_REPOSITORY'),
    },
    SERVICES: {
        COMMAND: Symbol('CATEGORY_COMMAND_SERVICE'),
        QUERY: Symbol('CATEGORY_QUERY_SERVICE'),
        CATEGORY: Symbol('CATEGORY_SERVICE'),
    },
};
