export const BANNER_COMMAND_REPOSITORY = Symbol('BANNER_COMMAND_REPOSITORY');
export const BANNER_QUERY_REPOSITORY = Symbol('BANNER_QUERY_REPOSITORY');
export const BANNER_MEDIA_UPLOAD_HANDLER = Symbol('BANNER_MEDIA_UPLOAD_HANDLER');
export const BANNER_MEDIA_DELETE_HANDLER = Symbol('BANNER_MEDIA_DELETE_HANDLER');
